### ISSUE TITLE
GNOME corrupting the data structures

### ISSUE THREAD

**Issue by disdi** [disdi/hepunion#2]
Ubuntu 13.04 saket-VirtualBox ttyS0

saket-VirtualBox login: [   67.737394] ISO 9660 Extensions: Microsoft Joliet Level 3
[   67.762609] ISO 9660 Extensions: RRIP_1991A
[  189.903851] systemd-hostnamed[2086]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
[  479.339440] HEPunion hepunion_read_super:251:mount[2571]: hepunion_read_super: ffff88000bc13800, ffff88000bc92000, 0, 23:56:31
[  479.390484] HEPunion get_branches:61:mount[2571]: get_branches: ffff88000bc13800, /tmp/root/=RW:/tmp/snapshot/=RO
[  479.495570] HEPunion make_path:23:mount[2571]: make_path: /tmp/root/=RW:/tmp/snapshot/=RO, 10, ffff88003b18bda8
[  479.684382] HEPunion make_path:23:mount[2571]: make_path: /tmp/snapshot/=RO, 14, ffff88003b18bda8
[  479.698257] HEPunion get_branches:163:mount[2571]: Read-write: /tmp/root
[  479.698257] Read-only: /tmp/snapshot
[  479.713779] HEPunion get_branches:164:mount[2571]: Read-write length: 9
[  479.713779] Read-only length: 13
[  479.769547] HEPunion hepunion_read_super:289:mount[2571]: Mount OK
[  479.793278] HEPunion hepunion_permission:752:mount[2571]: hepunion_permission: ffff88002b1f3180, 0X12
[  479.815060] HEPunion hepunion_permission:766:mount[2571]: before get relative path
[  479.828220] HEPunion get_relative_path:457:mount[2571]: get_relative_path: ffff88002b1f3180,           (null), ffff88003ae18000, ffff88003ae18040, 1
[  479.885581] HEPunion get_full_path_i:340:mount[2571]: get_full_path_i: ffff88002b1f3180, ffff88003d1c1000
[  479.908993] HEPunion get_full_path_d:366:mount[2571]: get_full_path_d: ffff88002b3cea80, ffff88003d1c1000
[  479.928286] HEPunion get_full_path_d:367:mount[2571]: Getting full path of: /
[  479.953335] HEPunion get_full_path_d:406:mount[2571]: Full path: /
[  479.978753] HEPunion hepunion_permission:769:mount[2571]: after get relative path:          (null), /
[  479.999386] HEPunion hepunion_permission:777:mount[2571]: before find_file:
[  480.015029] HEPunion find_file:213:mount[2571]: find_file: /, ffff88003ae19040, ffff88003ae18000, 0
[  480.035020] HEPunion find_file:224:mount[2571]: before can_exist
[  480.047904] HEPunion check_exist:183:mount[2571]: before push_root in check_exist
[  480.181420] HEPunion check_exist:185:mount[2571]: after push_root in check_exist
[  480.190361] HEPunion check_exist:189:mount[2571]: before kern_path in check_exist
[  480.203558] HEPunion check_exist:191:mount[2571]: after kern_path  in check_exist          (null)
[  480.214957] HEPunion check_exist:193:mount[2571]: before pop_root in check_exist
[  480.221833] HEPunion check_exist:195:mount[2571]: after pop_root in check_exist
[  480.228714] HEPunion find_file:226:mount[2571]: after can_exist           (null)
[  480.242327] HEPunion find_file:234:mount[2571]: before can_traverse
[  480.252227] HEPunion can_traverse:116:mount[2571]: can_traverse: /, ffff88003ae18000
[  480.264001] HEPunion find_file:236:mount[2571]: after can_traverse
[  480.272209] HEPunion hepunion_permission:779:mount[2571]: after find_file:0000000000000001
[  480.284235] HEPunion can_access:21:mount[2571]: can_access: /, /tmp/root/, ffff88003ae18000, 12
[  480.295331] HEPunion get_file_attr_worker:130:mount[2571]: get_file_attr_worker: /, /tmp/root/, ffff88003ae18000, ffff88003b18bdd8
[  480.372618] HEPunion find_me:87:mount[2571]: find_me: /, ffff88003ae18000, ffff88003d1c1000, ffff88003b18bd20
[  480.385826] HEPunion path_to_special:533:mount[2571]: path_to_special: /, 0, ffff88003d1c1000
[  480.395926] HEPunion lstat:598:mount[2571]: lstat: /tmp/root/.me., ffff88003b18bd20
[  480.403767] HEPunion get_file_attr_worker:140:mount[2571]: me file status: 0
[  480.411252] HEPunion lstat:598:mount[2571]: lstat: /tmp/root/, ffff88003b18bdd8
[  494.682169] HEPunion hepunion_getattr:171:bash[1947]: hepunion_getattr: ffff88000bf39d20, ffff88002b3cea80, ffff88000bc9df08
[  494.723030] HEPunion get_relative_path:457:bash[1947]: get_relative_path:           (null), ffff88002b3cea80, ffff88003ae18000, ffff88003ae18040, 1
[  494.752386] HEPunion get_full_path_d:366:bash[1947]: get_full_path_d: ffff88002b3cea80, ffff88003d5d9000
[  494.771279] HEPunion get_full_path_d:367:bash[1947]: Getting full path of: /
[  494.790151] HEPunion get_full_path_d:406:bash[1947]: Full path: /
[  494.802794] HEPunion get_file_attr:104:bash[1947]: get_file_attr: /, ffff88003ae18000, ffff88000bc9df08
[  494.825908] HEPunion find_file:213:bash[1947]: find_file: /, ffff88003d1c1000, ffff88003ae18000, 0
[  494.849809] HEPunion find_file:224:bash[1947]: before can_exist
[  494.861092] HEPunion check_exist:183:bash[1947]: before push_root in check_exist
[  494.882641] HEPunion check_exist:185:bash[1947]: after push_root in check_exist
[  494.900222] HEPunion check_exist:189:bash[1947]: before kern_path in check_exist
[  494.914239] HEPunion check_exist:191:bash[1947]: after kern_path  in check_exist          (null)
[  494.931821] HEPunion check_exist:193:bash[1947]: before pop_root in check_exist
[  494.948273] HEPunion check_exist:195:bash[1947]: after pop_root in check_exist
[  494.961004] HEPunion find_file:226:bash[1947]: after can_exist           (null)
[  494.973110] HEPunion find_file:234:bash[1947]: before can_traverse
[  494.984011] HEPunion can_traverse:116:bash[1947]: can_traverse: /, ffff88003ae18000
[  495.004011] HEPunion find_file:236:bash[1947]: after can_traverse
[  495.022950] HEPunion get_file_attr_worker:130:bash[1947]: get_file_attr_worker: /, /tmp/root/, ffff88003ae18000, ffff88000bc9df08
[  495.051489] HEPunion find_me:87:bash[1947]: find_me: /, ffff88003ae18000, ffff88003b44f000, ffff88000bc9dd40
[  495.067602] HEPunion path_to_special:533:bash[1947]: path_to_special: /, 0, ffff88003b44f000
[  495.079014] HEPunion lstat:598:bash[1947]: lstat: /tmp/root/.me., ffff88000bc9dd40
[  495.086352] HEPunion get_file_attr_worker:140:bash[1947]: me file status: 0
[  495.097727] HEPunion lstat:598:bash[1947]: lstat: /tmp/root/, ffff88000bc9df08
[  495.122621] HEPunion hepunion_permission:752:bash[1947]: hepunion_permission: ffff88002b1f3180, 0X41
[  495.145211] HEPunion hepunion_permission:766:bash[1947]: before get relative path
[  495.158780] HEPunion get_relative_path:457:bash[1947]: get_relative_path: ffff88002b1f3180,           (null), ffff88003ae18000, ffff88003ae18040, 1
[  495.182305] HEPunion get_full_path_i:340:bash[1947]: get_full_path_i: ffff88002b1f3180, ffff88003b44f000
[  495.198571] HEPunion get_full_path_d:366:bash[1947]: get_full_path_d: ffff88002b3cea80, ffff88003b44f000
[  495.208005] HEPunion get_full_path_d:367:bash[1947]: Getting full path of: /
[  495.218994] HEPunion get_full_path_d:406:bash[1947]: Full path: /
[  495.234765] HEPunion hepunion_permission:769:bash[1947]: after get relative path:          (null), /
[  495.252207] HEPunion hepunion_permission:777:bash[1947]: before find_file:
[  495.263565] HEPunion find_file:213:bash[1947]: find_file: /, ffff88003ae19040, ffff88003ae18000, 0
[  495.279255] HEPunion find_file:224:bash[1947]: before can_exist
[  495.294827] HEPunion check_exist:183:bash[1947]: before push_root in check_exist
[  495.383883] HEPunion check_exist:185:bash[1947]: after push_root in check_exist
[  495.399989] HEPunion check_exist:189:bash[1947]: before kern_path in check_exist
[  495.414463] HEPunion check_exist:191:bash[1947]: after kern_path  in check_exist          (null)
[  495.438471] HEPunion check_exist:193:bash[1947]: before pop_root in check_exist
[  495.448002] HEPunion check_exist:195:bash[1947]: after pop_root in check_exist
[  495.463473] HEPunion find_file:226:bash[1947]: after can_exist           (null)
[  495.479089] HEPunion find_file:234:bash[1947]: before can_traverse
[  495.493995] HEPunion can_traverse:116:bash[1947]: can_traverse: /, ffff88003ae18000
[  495.546101] HEPunion find_file:236:bash[1947]: after can_traverse
[  495.562075] HEPunion hepunion_permission:779:bash[1947]: after find_file:0000000000000001
[  495.567630] HEPunion can_access:21:bash[1947]: can_access: /, /tmp/root/, ffff88003ae18000, 41
[  495.585825] HEPunion get_file_attr_worker:130:bash[1947]: get_file_attr_worker: /, /tmp/root/, ffff88003ae18000, ffff88000bc9de18
[  495.685112] HEPunion find_me:87:bash[1947]: find_me: /, ffff88003ae18000, ffff88003b44f000, ffff88000bc9dd60
[  495.697291] HEPunion path_to_special:533:bash[1947]: path_to_special: /, 0, ffff88003b44f000
[  495.707838] HEPunion lstat:598:bash[1947]: lstat: /tmp/root/.me., ffff88000bc9dd60
[  495.749960] HEPunion get_file_attr_worker:140:bash[1947]: me file status: 0
[  495.763634] HEPunion lstat:598:bash[1947]: lstat: /tmp/root/, ffff88000bc9de18
[  498.939813] HEPunion hepunion_permission:752:bash[1947]: hepunion_permission: ffff88002b1f3180, 0X81
[  498.989094] HEPunion hepunion_permission:766:bash[1947]: before get relative path
[  499.042210] HEPunion get_relative_path:457:bash[1947]: get_relative_path: ffff88002b1f3180,           (null), ffff88003ae18000, ffff88003ae18040, 1
[  524.188183] BUG: soft lockup - CPU#0 stuck for 23s! [gnome-settings-:1392]

**Comment by disdi** [comment]
This shows driver we really corrupt the kernel. We need some locking mechanisms in our driver to protect the data-structures.

**Comment by loicbr** [comment]
I think gnome does not corrupt anything. It is probably just accessing all mounted filesystems for any reason (that's why smart environments like gnome and kde slows at lot the os: they try to be smart. The reason there could be to be able to show in some config panel these mounted filesystems).

The problem there could be that HEPunion does not permit yet 2 actions on the same time.

**Comment by disdi** [comment]
The VFS(Virtual Filesystem) configures the permission of our filesystem through permission system call in inode operation structure which in our case is
https://github.com/HeisSpiter/hepunion/blob/master/fs/hepunion/opts.c#L1673

Now if we go through our hepunion_permission, it calls get_relative path and if we look at the log, last call before kernel hangs is this function message
[ 499.042210] HEPunion get_relative_path:457:bash[1947]: get_relative_path: ffff88002b1f3180, (null), ffff88003ae18000, ffff88003ae18040, 1

 so kernel hangs somewhere here-
https://github.com/HeisSpiter/hepunion/blob/master/fs/hepunion/helpers.c#L452
Now this is where the real path allocation takes place in the memory. So why would gnome interfere with this in any circumstances?

Another most astonishing thing is this that during mount also hepunion_permission was called and was completed successfully-
From the log above-
[ 479.769547] HEPunion hepunion_read_super:289:mount[2571]: Mount OK
[ 479.793278] HEPunion hepunion_permission:752:mount[2571]: hepunion_permission: ffff88002b1f3180, 0X12
[ 479.815060] HEPunion hepunion_permission:766:mount[2571]: before get relative path
[ 479.828220] HEPunion get_relative_path:457:mount[2571]: get_relative_path: ffff88002b1f3180, (null), ffff88003ae18000, ffff88003ae18040, 1
[ 479.885581] HEPunion get_full_path_i:340:mount[2571]: get_full_path_i: ffff88002b1f3180, ffff88003d1c1000
[ 479.908993] HEPunion get_full_path_d:366:mount[2571]: get_full_path_d: ffff88002b3cea80, ffff88003d1c1000
[ 479.928286] HEPunion get_full_path_d:367:mount[2571]: Getting full path of: /
[ 479.953335] HEPunion get_full_path_d:406:mount[2571]: Full path: /
[ 479.978753] HEPunion hepunion_permission:769:mount[2571]: after get relative path: (null), /

So why is it failing the second time?
