### ISSUE TITLE
dcache_lock replacement

### ISSUE THREAD

**Issue by disdi** [disdi/hepunion#3]
When the driver was ported to 3.8 kernel, we removed dcache_lock since its no longer supported. I specifically list down the link in the code where this dcache-lock is present in 2.6.18 kernel and is absent in 3.8 kernel below -

 https://github.com/HeisSpiter/hepunion/blob/master/fs/hepunion/helpers.c#L373 

Now since its no longer supported, its replacement would be-
1. If I need to protect my driver from itself, it can add its own locking.
2.  If the problem is that dcache_lock is used to protect critical variables from other parts of the kernel, I have two options-
   a) I will need to restructure my code to avoid the issue
   b) I need to find other suitable locking.

https://github.com/HeisSpiter/hepunion/blob/master/fs/hepunion/helpers.c#L373

hepunion_permission 
hepunion_getattr 

are called by the VFS since they are mapped to 
.getattr
.permission
in inode_operations  structure
https://github.com/HeisSpiter/hepunion/blob/8ce91306a302afe797af09b0831d312ad87e495a/fs/hepunion/opts.c#L1666

Now if you look at the function definition, you would find that both of them use 
get_relative_path and pass inode or dentry respectively.

Inside this function either
a)get_full_path_d(dentry, real_path);//called if dentry is sent

b)get_full_path_i(inode, real_path);//called if inode is sent

Now inside get_full_path_i ultimately get_full_path_d gets called ultimately.

Now inside get_full_path_d only, we implement our dcache_lock  to calculate the path.

Conclusion- So I conclude that in our code "dcache_lock"  was used to protect critical variables from other parts of the kernel.

So what is the correct replacement in 3.8 kernel to suit exactly our drivers ?

**Comment by disdi** [comment]
Below link states that replacing dcache_lock in our file-system driver is the the single most prominent and difficult task and would require through study and understanding

http://lwn.net/Articles/422637/

Linus Trovalds stopped the kernel merge window when making this change. I would like to quote Linus-

"It's scary because this is some very core code, and the new RCU lookup model is way more clever and subtle than the old dentry_lock spinlock."

 from the below link-
http://lwn.net/Articles/422641/

I would also like to qoute Nick Piggin, the developer who added this change to the main line kernel,- 

"The rcu-walk stuff can be more tricky for your filesystem to take advantage of. If you supply a .d_revalidate, .permission, or .check_acl, then path walking is going to be slow and unscalable for you.Out of tree filesystems: you _have_ to at least add a line of code to the above functions in order to specify that you don't want to participate in rcu-walk."

from the below link-
http://lwn.net/Articles/422643/

**Comment by loicbr** [comment]
To better understand the 1st comment, I would like to know what is 'RCU lookup' / 'rcu-walk' / 'path walking' generally and in our case.

Also, do you consider hepUnion to be 'In Tree' or 'Out of Tree' ?

**Comment by disdi** [comment]
Path resolution is the finding a dentry corresponding to a path name string, by performing a path walk. 

Paths are resolved by walking the namespace tree, starting with the first component of the pathname (eg. root or cwd) with a known dentry, then finding the child of that dentry, which is named the next component in the path string. Then repeating the lookup from the child dentry and finding its child with the next element, and so on.

Kindly have a look at the below image-
http://lwn.net/images/ns/kernel/dentry.png

In our driver code it is done here in the function-
 int get_full_path_d(const struct dentry *dentry, char *real_path) at the below link-
https://github.com/disdi/hepunion/blob/master/fs/hepunion/helpers.c#L375

Coming back to theory, this requires taking a lock and reference count on the dentry that was looked up, so that may be used as the basis for walking the next path element. This is inefficient and unscalable. 
1. It is inefficient because  of the locks and atomic operations required for every dentry element slows things down.
2. It is not scalable because many parallel applications that are path-walk intensive tend to do path lookups starting from a common dentry (usually, the root "/" or current working directory). So contention on these common path elements causes lock and cacheline queueing.

Since 2.6.38, RCU is used to make a significant part of the entire path walk (including dcache look-up) completely "store-free" (so, no locks, atomics, or even stores into cachelines of common dentries). This is known as "rcu-walk" path walking.

So Path walking in kernel is now done in two distinct modes
1.  ref-walk -   ref-walk- is the traditional way of performing dcache lookups using d_lock to serialise concurrent modifications to the dentry and take a reference count on it. Ref-walk is simple and obvious, and may sleep, take locks, etc while path walking is operating on each dentry. 
2.  rcu-walk -  rcu-walk uses seqcount based dentry lookups, and can perform lookup of intermediate elements without any stores to shared data in the dentry or inode.

"rcu-walk can not be applied to all cases, eg. if the filesystem must sleep or perform non trivial operations, rcu-walk must be switched to ref-walk mode."

Where ref-walk uses a stable, refcounted ``parent'' to walk the remaining path string, rcu-walk uses a d_seq protected snapshot. When looking up a child of this parent snapshot, we open d_seq critical section on the child
before closing d_seq critical section on the parent. This gives an interlocking ladder of snapshots to walk down.
Something like the below link-
http://spatula-city.org/~im14u2c/images/man_running_up_crumbling_stairs.jpg

> > Also, do you consider hepUnion to be 'In Tree' or 'Out of Tree' ?
> > With my view of hepUnion, it is not purely a 'In Tree' filesystem.
> >  Lets look at the logs our unstable driver on 3.8 kernel at the below link-
> > https://github.com/disdi/hepunion/issues/5

If we look at the mount command issued
mount -t HEPunion -o /tmp/root/=RW:/tmp/snapshot/=RO none /tmp/export/
and then look at the logs of mount command between //MOUNT COMMAND// tags

we see that actually we create only one filesystem(RW) which the kernel(Virtual Filesystem) interacts with. The other RO filesystem is a virtual concept which we materialize by our module code.

I would also like to inform that issue of gnome- corrupting our driver https://github.com/disdi/hepunion/issues/2  is happening at just where we are doing path_lookup in our code on 3.8 kernel.

**Comment by disdi** [comment]
First let us assume there is some lock X ,now during ls there are 10 function calls.
Also each function call the other function, like this 1->2->3->4..->10 
Suppose function 1 takes the lock X ...and  now function 6 also tries to take the same lock X.
so what will happen?
so function 6 will wait....infinitely.
 thats deadlock 

Now coming back to our problem, 

Please let us follow the path "ls"  in the kernel-
1. filp_open(/tmp/root/) 
2, path_openat() 
3. path_init() - takes lock 
4. path_init returns, so back in path_openat() 
5. path_openat()-> link_path_walk() 
6. link_path_walk()-> may_lookup
7. may_lookup->permission() 
8.permission() ->hepunion_permission() 
9.hepunion_permission() -.kern-path()
10.kern-path->do_path_lookup->filename_lookup->path_lookupat->path_init
http://lxr.free-electrons.com/source/fs/namei.c?v=3.8#L1961

We are in a DEADLOCK. WE HAVE GOT THE PROBLEM.

so we cant use KERN-PATH. We simply can't. 

Now let us see why we need kern_path?
lets refer to https://github.com/disdi/hepunion/issues/6 diagram and my understanding of our filesystem architecture.
 See
 1.I get my inode from VFS
 2.find its relative path
 3.send it to kern_path to get the real path
 4.compare them and see whether we can merge it 
5. do stat on it
This is how we always check our permission. This is our filesystem design. With this design we have to use kern_path at all cost.

Now I looked at unionfs, how they are doing it.

http://git.fsl.cs.sunysb.edu/?p=unionfs-2.6.18.y.git;a=blob;f=fs/unionfs/inode.c;h=e1200ea095531763f2c7856c36f52615fb521ff0;hb=b988dca16bba3d55ada4d087a1fb1305d7523086#l769

They warn us against this situation only at this comment. Unlike us (we deal with relative path and real path), they deal with inodes.
They use something like unionfs_lower_inode_idx  which helps them deal only in inodes.
That is their design and so they do not have to use kern-path and "ls' is fine for them 

Why this issue did not rise on 2.6.18?
they were not using kern_path which uses lock.
So why its alternative path_lookup on 2.6.18 did not need locks?
VFS was not using RCU-lookup.

In RCU-lookup if I need to go this way 1->2->3, I take a lock on 1 and then go to 2 and then 3(something like this) 

Something like the below link-
http://spatula-city.org/~im14u2c/images/man_running_up_crumbling_stairs.jpg

which was not there in 2.6.18 kernel.

CONCLUSION-I conclude there is a design issue of our filesystem on newer kernels which use RCU-walking
